title: Chihab Eddine Liefrid
logo: /photo.jpeg
description: Étudiant en Master en Intelligence Artificielle et Science des Données à la Faculté des Sciences et techniques de Tanger.
show_downloads: false
theme: jekyll-theme-minimal
